// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:simple_live_app/models/db/follow_user.dart';
import 'package:simple_live_app/models/db/follow_user_tag.dart';
import 'package:simple_live_app/models/db/history.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(FollowUserAdapter());
    registerAdapter(FollowUserTagAdapter());
    registerAdapter(HistoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(FollowUserAdapter());
    registerAdapter(FollowUserTagAdapter());
    registerAdapter(HistoryAdapter());
  }
}
